# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadcast.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62roadcast.proto\"@\n\x10\x62roadcastRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06socket\x18\x02 \x01(\t\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x05\"3\n\x0f\x62roadcastResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2?\n\tbroadcast\x12\x32\n\tbroadcast\x12\x11.broadcastRequest\x1a\x10.broadcastResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broadcast_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BROADCASTREQUEST']._serialized_start=19
  _globals['_BROADCASTREQUEST']._serialized_end=83
  _globals['_BROADCASTRESULT']._serialized_start=85
  _globals['_BROADCASTRESULT']._serialized_end=136
  _globals['_BROADCAST']._serialized_start=138
  _globals['_BROADCAST']._serialized_end=201
# @@protoc_insertion_point(module_scope)
