# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import broadcast_pb2 as broadcast__pb2


class broadcastStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.broadcast = channel.unary_unary(
                '/broadcast/broadcast',
                request_serializer=broadcast__pb2.broadcastRequest.SerializeToString,
                response_deserializer=broadcast__pb2.broadcastResult.FromString,
                )


class broadcastServicer(object):
    """Missing associated documentation comment in .proto file."""

    def broadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_broadcastServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'broadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.broadcast,
                    request_deserializer=broadcast__pb2.broadcastRequest.FromString,
                    response_serializer=broadcast__pb2.broadcastResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broadcast', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class broadcast(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def broadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broadcast/broadcast',
            broadcast__pb2.broadcastRequest.SerializeToString,
            broadcast__pb2.broadcastResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
