# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Bucket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x42ucket.proto\"+\n\nobjectInfo\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06socket\x18\x02 \x01(\t\"(\n\tfindReply\x12\x0b\n\x03suc\x18\x01 \x01(\x08\x12\x0e\n\x06socket\x18\x02 \x03(\t\"\x1e\n\x0b\x63hatMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd2\x01\n\x07Routing\x12\'\n\nobjectFind\x12\x0b.objectInfo\x1a\n.findReply\"\x00\x12&\n\tuserLogin\x12\x0b.objectInfo\x1a\n.findReply\"\x00\x12\'\n\nuserLogoff\x12\x0b.objectInfo\x1a\n.findReply\"\x00\x12%\n\x08joinRoom\x12\x0b.objectInfo\x1a\n.findReply\"\x00\x12&\n\tleaveRoom\x12\x0b.objectInfo\x1a\n.findReply\"\x00\x32*\n\x04\x63hat\x12\"\n\x04send\x12\x0c.chatMessage\x1a\n.findReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Bucket_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJECTINFO']._serialized_start=16
  _globals['_OBJECTINFO']._serialized_end=59
  _globals['_FINDREPLY']._serialized_start=61
  _globals['_FINDREPLY']._serialized_end=101
  _globals['_CHATMESSAGE']._serialized_start=103
  _globals['_CHATMESSAGE']._serialized_end=133
  _globals['_ROUTING']._serialized_start=136
  _globals['_ROUTING']._serialized_end=346
  _globals['_CHAT']._serialized_start=348
  _globals['_CHAT']._serialized_end=390
# @@protoc_insertion_point(module_scope)
